runtime: nodejs10
service: newcmms-server
instance_class: F1
inbound_services:
  - warmup

automatic_scaling:
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5
  max_concurrent_requests: 10
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: 30ms

