# For markdown refer to https://spec.commonmark.org/0.27
openapi: 3.0.2
info:
  title: NewCMMS public REST API
  version: 1.0.0
  contact:
    name: Bogdan Shevchenko
    url: https://github.com/shevchenkobn
    email: bohdan.shevchenko1@nure.ua
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api/v1
    description: The server will be served from the same host as this document.
tags:
  - name: auth
    description: API to manage auth tokens
  - name: users
    description: API to manage users
paths: {} # To be defined and populated from the source code
components:
  securitySchemes:
    jwt-bearer:
      $ref: './security-schemes/jwt-bearer.yaml'
  schemas:
    $ref: ./schemas/__init__.yaml
  responses:
    $ref: ./responses/__init__.yaml

