server:
  host: 0.0.0.0
  port: 3000
  openApiDocsPrefix: /
  admin:
    id: 1
    name: Master Admin
    password: Admin!123
    email: master.admin@local.host

db:
  type: pg
  host: 127.0.0.1
  database: newcmms
  user: yourUser
  password: yourPass
  debug: false # will matter only if NODE_ENV is production

mqtt:
  broker:
    protocol: mqtt
    host: 127.0.0.1
    port: 1883 # to override set null
    #username: yourUser # to override set null
    #password: yourPass # to override set null
  clusterMode: true # use Shared Subscriptions by server clusters

cors:
  whitelist:
    - '*'
  methods:
    - GET
    - POST
    - DELETE
    - PUT
    - PATCH

auth:
  jwt:
    expiration: # NO MONTH ABBREVIATION AVAILABLE. For format refer to https://www.npmjs.com/package/ms or try from node CLI
      accessToken: 2h
      refreshToken: 0.5y
    issuer: NewCMMS
    algorithms:
      accessToken: PS256
      refreshToken: PS512
    keys: # Keys are needed for tokens' signature
      folder: keys/
      filenames:
        accessToken:
          private: access_id_rsa
          public: access_id_rsa.pub
        refreshToken:
          private: refresh_id_rsa
          public: refresh_id_rsa.pub
      keyStrings: # Keys in pkcs format can be stored in the config. It is needed for multi-node deployments.
        accessToken:
          private:
          public:
        refreshToken:
          private:
          public:
